name: Puppeteer Canary CI

# Declare default permissions as read only.
permissions: read-all

on:
  pull_request:
  # workflow_dispatch:
  #   - 

jobs:
  canary-chrome-tests:
    name: canary ${{ matrix.suite }} tests on ${{ matrix.os }} (${{ matrix.shard }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          # - windows-latest
          # - macos-latest
        suite:
          - chrome-headless
          # - chrome-headful
          # - chrome-new-headless
          # - chrome-bidi return once redefine is installed
        shard:
          - 1-2
          - 2-2
        exclude:
          - os: windows-latest
            suite: chrome-bidi
          - os: macos-latest
            suite: chrome-headful
    steps:
      - name: Check out repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: Set up Node.js
        uses: actions/setup-node@b39b52d1213e96004bfcb1c61a8a6fa8ab84f3e8 # v4.0.1
        with:
          cache: npm
          node-version: lts/*

      - name: Set up FFmpeg
        uses: FedericoCarboni/setup-ffmpeg@5058c9851b649ced05c3e73a4fb5ef2995a89127 # v2.0.0

      - name: Install dependencies
        run: npm ci
        env:
          PUPPETEER_SKIP_DOWNLOAD: true
      # Set up GitHub Actions caching for Wireit.
      - uses: google/wireit@f3a3c79c553122e2fe5829eeac7d815326502903 # setup-github-actions-caching/v1

      # - name: Install Redefine
      #   env:
      #     REDEFINE_AUTH: "5cea7dd8-37ec-4b65-ade4-969cf5f27ac7::8a287b06-a121-40e4-bb7f-bcbb75844b2b"
      #   run: |
      #     pip --version 
      #     python --version
      #     pip install redefine -I -U --index-url https://pip.redefine.dev/staging

      #     redefine config set environment=staging 
      #     redefine config set redefine_address=dune-tf-staging.redefine.dev
      #     redefine config set log_to_file=true
      #     redefine config set stable_branch=main

      #     redefine start --prioritize --mocha --verbose

      - name: Build packages
        run: npm run build --workspace @puppeteer-test/test

      - name: Install Chrome Canary
        id: browser
        run: node tools/download_chrome_bidi.mjs $HOME/.cache/puppeteer/chrome-canary

      - name: Run all tests (for Linux)
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: |
          echo "$PWD"
          cat ./.mocharc.yaml
          xvfb-run --auto-servernum npm run test -- --shard '${{ matrix.shard }}' --test-suite ${{ matrix.suite }} --save-stats-to /tmp/artifacts/${{ github.event_name }}_INSERTID.json --config=./.mocharc.yaml
        env:
          PUPPETEER_EXECUTABLE_PATH: ${{ steps.browser.outputs.executablePath }}
      - uses: actions/upload-artifact@c7d193f32edcb7bfad88892161225aeda64e9392 # v4.0.0
        if: always()
        with:
          name: test-results-${{ matrix.os }}-${{ matrix.suite }}-${{ matrix.shard }}
          path: /tmp/artifacts/*.json
